RazorPagesApp/Models/PromoCode.cs
using System;

namespace RazorPagesApp.Models
{
    public class PromoCode
        : BaseEntity
    {
        public string Code { get; set; }

        public string ServiceInfo { get; set; }

        public DateTime BeginDate { get; set; }

        public DateTime EndDate { get; set; }

        public Guid PartnerId { get; set; }

        public virtual Partner Partner { get; set; }
        
        public Guid? PartnerManagerId { get; set; }
        
        public virtual Preference Preference { get; set; }

        public Guid PreferenceId { get; set; }
    }
}

RazorPagesApp/Pages/Customers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Customers
{
    public class CreateModel : PageModel
    {
        public List<Customer> CustomerList { get; set; }
        private readonly IRepository<Customer> _customerRepository;

        [BindProperty]
        public Customer Customer { get; set; }
        public string Message { get; private set; }

        public CreateModel(IRepository<Customer> customerRepository)
        {
            _customerRepository = customerRepository;
            Customer = new Customer
            {
                Id = Guid.NewGuid()
            };
        }


        public void OnGet()
        {
            Message = "";
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Message = "Введены некорректные данные!";
                return Page();
            }

            try
            {
                await _customerRepository.AddAsync(Customer);
                return RedirectToPage("List");
            }
            catch
            {
                return BadRequest($"Failed to create new customer");
            }

        }
    }
}

RazorPagesApp/Pages/Customers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Customers
{
    public class EditModel : PageModel
    {
        public List<Customer> CustomerList { get; set; }
        private readonly IRepository<Customer> _customerRepository;

        [BindProperty]
        public Customer Customer { get; set; }
        public string Message { get; private set; }

        public EditModel(IRepository<Customer> customerRepository)
        {
            _customerRepository = customerRepository;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            var guid = Guid.Parse(id);
            Customer = await _customerRepository.GetByIdAsync(guid);

            if (Customer == null)
                return NotFound();

            Message = "";
            return Page();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Message = "Введены некорректные данные!";
                return Page();
            }

            try
            {
                await _customerRepository.UpdateAsync(Customer);
                return RedirectToPage("List");
            }
            catch
            {
                return BadRequest($"Failed to update сustomer with id: {Customer.Id}");
            }
        }
    }
}

RazorPagesApp/Pages/Customers/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Customers
{
    public class ListModel : PageModel
    {
        public List<Customer> CustomerList { get; set; }
        private readonly IRepository<Customer> _customerRepository;

        public ListModel(IRepository<Customer> customerRepository)
        {
            _customerRepository = customerRepository;
        }

        
        public async Task OnGetAsync()
        {
            var customers = await _customerRepository.GetAllAsync();
            CustomerList = customers.ToList();
        }


        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            try
            {
                var customer = await _customerRepository.GetByIdAsync(id);
                await _customerRepository.DeleteAsync(customer);
                return RedirectToPage();
            }
            catch
            {
                return BadRequest($"Failed to delete customer with id: {id}");
            }            
        }
    }
}

RazorPagesApp/Pages/Employees/Create.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Employees
{
    public class CreateModel : PageModel
    {
        private readonly IRepository<Employee> _employeeRepository;
        private readonly IRepository<Role> _rolesRepository;

        [BindProperty]
        public Employee Employee { get; set; }
        public string Message { get; private set; }


        public CreateModel(IRepository<Employee> employeeRepository, IRepository<Role> rolesRepository)
        {
            _employeeRepository = employeeRepository;
            _rolesRepository = rolesRepository;
            Employee = new Employee
            {
                Id = Guid.NewGuid()
            };
        }


        public void OnGet()
        {
            Message = "";
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Message = "Введены некорректные данные!";
                return Page();
            }

            // Проверка правильности написания роли
            var roles = await _rolesRepository.GetAllAsync();
            var roleList = roles.Select(x => x.Name).ToList();
            var roleIsValid = roleList.Where(x => x == Employee.Role.Name).Any();
            if (!roleIsValid)
            {
                Message = "Ошибка в написании роли";
                return Page();
            }

            try
            {
                Employee.Role = roles.SingleOrDefault(x => x.Name == Employee.Role.Name);
                await _employeeRepository.AddAsync(Employee);
                return RedirectToPage("List");
            }
            catch
            {
                return BadRequest($"Failed to create new employee");
            }

        }
    }
}

RazorPagesApp/Pages/Employees/Edit.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;

namespace RazorPagesApp.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly Repositories.IRepository<Employee> _employeeRepository;
        private readonly Repositories.IRepository<Role> _rolesRepository;

        [BindProperty]
        public Employee Employee { get; set; }
        public string Message { get; private set; }

        public EditModel(Repositories.IRepository<Employee> employeeRepository, Repositories.IRepository<Role> rolesRepository)
        {
            _employeeRepository = employeeRepository;
            _rolesRepository = rolesRepository;
        }


        public async Task<IActionResult> OnGetAsync(string id)
        {
            var guid = Guid.Parse(id);
            Employee = await _employeeRepository.GetByIdAsync(guid);

            if (Employee == null)
                return NotFound();

            Message = "";
            return Page();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Message = "Введены некорректные данные!";
                return Page();
            }

            // Проверка правильности написания роли
            var roles = await _rolesRepository.GetAllAsync();
            var roleList = roles.Select(x => x.Name).ToList();
            var roleIsValid = roleList.Where(x => x == Employee.Role.Name).Any();
            if (!roleIsValid)
            {
                Message = "Ошибка в написании роли";
                return Page();
            }

            try
            {
                Employee.Role = roles.SingleOrDefault(x => x.Name == Employee.Role.Name);
                await _employeeRepository.UpdateAsync(Employee);
                return RedirectToPage("List");
            }
            catch
            {
                return BadRequest($"Failed to update employee with id: {Employee.Id}");
            }
        }
    }
}

RazorPagesApp/Pages/Employees/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Employees
{
    public class ListModel : PageModel
    {
        public List<Employee> EmployeeList { get; set; }
        private readonly IRepository<Employee> _employeeRepository;

        public ListModel(IRepository<Employee> employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public async Task OnGetAsync()
        {
            var employees = await _employeeRepository.GetAllAsync();
            EmployeeList = employees.ToList();

        }


        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            try
            {
                var employee = await _employeeRepository.GetByIdAsync(id);
                await _employeeRepository.DeleteAsync(employee);
                return RedirectToPage();
            }
            catch
            {
                return BadRequest($"Failed to delete employee with id: {id}");
            }            
        }
    }
}

RazorPagesApp/Pages/Preferences/Create.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Preferences
{
    public class CreateModel : PageModel
    {
        private readonly IRepository<Preference> _preferenceRepository;

        [BindProperty]
        public Preference Preference { get; set; }
        public string Message { get; private set; }

        public CreateModel(IRepository<Preference> preferenceRepository)
        {
            _preferenceRepository = preferenceRepository;
            Preference = new Preference
            {
                Id = Guid.NewGuid()
            };
        }


        public void OnGet()
        {
            Message = "";
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Message = "Введены некорректные данные!";
                return Page();
            }

            try
            {
                await _preferenceRepository.AddAsync(Preference);
                return RedirectToPage("List");
            }
            catch
            {
                return BadRequest($"Failed to create new preference");
            }

        }
    }
}

RazorPagesApp/Pages/Preferences/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Preferences
{
    public class EditModel : PageModel
    {
        private readonly IRepository<Preference> _preferenceRepository;

        [BindProperty]
        public Preference Preference { get; set; }
        public string Message { get; private set; }

        public EditModel(IRepository<Preference> preferenceRepository)
        {
            _preferenceRepository = preferenceRepository;
        }


        public async Task<IActionResult> OnGetAsync(string id)
        {
            var guid = Guid.Parse(id);
            Preference = await _preferenceRepository.GetByIdAsync(guid);

            if (Preference == null)
                return NotFound();
            
            Message = "";
            return Page();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Message = "Введены некорректные данные!";
                return Page();
            }

            try
            {
                await _preferenceRepository.UpdateAsync(Preference);
                return RedirectToPage("List");
            }
            catch
            {
                return BadRequest($"Failed to update preference with id: {Preference.Id}");
            }
        }
    }
}

RazorPagesApp/Pages/Preferences/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.Preferences
{
    public class ListModel : PageModel
    {
        public List<Preference> PreferenceList { get; set; }
        private readonly IRepository<Preference> _preferenceRepository;

        public ListModel(IRepository<Preference> preferenceRepository)
        {
            _preferenceRepository = preferenceRepository;
        }

        public async Task OnGetAsync()
        {
            var preferences = await _preferenceRepository.GetAllAsync();
            PreferenceList = preferences.ToList();
        }


        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            try
            {
                var preference = await _preferenceRepository.GetByIdAsync(id);
                await _preferenceRepository.DeleteAsync(preference);
                return RedirectToPage();
            }
            catch
            {
                return BadRequest($"Failed to delete preference with id: {id}");
            }
        }
    }
}

RazorPagesApp/Pages/PromoCodes/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesApp.Models;
using RazorPagesApp.Repositories;

namespace RazorPagesApp.Pages.PromoCodes
{
    public class ListModel : PageModel
    {
        public List<PromoCodeShow> PromoCodeList { get; set; } = new List<PromoCodeShow>();
        private readonly IRepository<PromoCode> _promoCodeRepository;
        private readonly IRepository<Preference> _preferenceRepository;
        private readonly IRepository<Role> _roleRepository;
        private readonly IRepository<Partner> _partnerRepository;

        public ListModel(IRepository<PromoCode> promoCodeRepository, IRepository<Preference> preferenceRepository,
            IRepository<Partner> partnerRepository, IRepository<Role> roleRepository)
        {
            _promoCodeRepository = promoCodeRepository;
            _preferenceRepository = preferenceRepository;
            _partnerRepository = partnerRepository;
            _roleRepository = roleRepository;
        }


        public async Task OnGetAsync()
        {
            var promoCodes = await _promoCodeRepository.GetAllAsync();
            var preferences = await _preferenceRepository.GetAllAsync();
            var partners = await _partnerRepository.GetAllAsync();
            var roles = await _roleRepository.GetAllAsync();
            
            foreach (var promoCode in promoCodes)
            {
                PromoCodeList.Add(new PromoCodeShow
                {
                    Id = promoCode.Id,
                    Code = promoCode.Code,
                    ServiceInfo = promoCode.ServiceInfo,
                    BeginDate = promoCode.BeginDate,
                    EndDate = promoCode.EndDate,
                    Partner = partners.Single(x => x.Id == promoCode.PartnerId).Name,
                    PartnerManager = roles.Single(x => x.Id == promoCode.PartnerManagerId).Name,
                    Preference = preferences.Single(x => x.Id == promoCode.PreferenceId).Name
                });
            }
        }


        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            try
            {
                var promoCode = await _promoCodeRepository.GetByIdAsync(id);
                await _promoCodeRepository.DeleteAsync(promoCode);
                return RedirectToPage();
            }
            catch
            {
                return BadRequest($"Failed to delete promoCode with id: {id}");
            }            
        }
    }
}

RazorPagesApp/Pages/PromoCodes/Create.cshtml
@page
@model RazorPagesApp.Pages.PromoCodes.CreateModel
@{
    ViewData["Title"] = "Добавить промокод";
    
}
<h3>@ViewData["Title"]</h3>

<div asp-validation-summary="All"></div>
<form method="POST">
    <div>
        <input asp-for="PromoCode.Id" type="hidden" />
        <span asp-validation-for="PromoCode.Id"></span>
    </div>
    <div>
        <label><b>Код</b></label><br />
        <input asp-for="PromoCode.Code" type="text" />
    </div>
    <div>
        <label><b>Информация</b></label><br />
        <input asp-for="PromoCode.ServiceInfo" type="text" size="100" />
    </div>
    <div>
        <label><b>От</b></label><br />
        <input asp-for="PromoCode.BeginDate" asp-format="{0:dd/MM/yyyy}" type="date" />
    </div>
    <div>
        <label><b>До</b></label><br />
        <input asp-for="PromoCode.EndDate" asp-format="{0:dd/MM/yyyy}" type="date" />
    </div>
    <div>
        <label><b>Партнер</b></label><br />
        <select asp-for="PartnerSelected" asp-items="Model.PartnerItems" style="width:300px;" ></select>
    </div>
    <div>
         <label><b>Сотрудник</b></label><br />
         <select asp-for="ManagerSelected" asp-items="Model.RoleItems" style="width:300px;" ></select>
     </div>
    <div>
        <label><b>Предпочтение</b></label><br />
        <select asp-for="PreferenceSelected" asp-items="Model.PreferenceItems" style="width:300px;" ></select>
    </div>
    <div>
        <br />
        <input type="submit" value="Сохранить" />
        <p>@Model.Message</p>
    </div>
</form>

RazorPagesApp/Pages/PromoCodes/Edit.cshtml
@page "{id:Guid}"
@model RazorPagesApp.Pages.PromoCodes.EditModel
@{
    ViewData["Title"] = "Редактирование промокода";
}
<h2>@ViewData["Title"]</h2>

<form method="post">
    <div asp-validation-summary="All"></div>
    <input asp-for="PromoCode.Id" type="hidden" />
    <div>
        <label><b>Код</b></label>
        <div>
            <input asp-for="PromoCode.Code" type="text" />
            <span asp-validation-for="PromoCode.Code"></span>
        </div>
    </div>
    <div>
        <label><b>Информация</b></label>
        <div>
            <input asp-for="PromoCode.ServiceInfo" type="text" size="100" />
            <span asp-validation-for="PromoCode.ServiceInfo"></span>
        </div>
    </div>
    <div>
        <label><b>От</b></label>
        <div>
            <input asp-for="PromoCode.BeginDate" asp-format="{0:dd/MM/yyyy}" type="text" />
            <span asp-validation-for="PromoCode.BeginDate"></span>
        </div>
    </div>
    <div>
        <label><b>До</b></label>
        <div>
            <input asp-for="PromoCode.EndDate" asp-format="{0:dd/MM/yyyy}" type="text" />
            <span asp-validation-for="PromoCode.EndDate"></span>
        </div>
    </div>
    <div>
        <label><b>Партнер</b></label><br />
        <select asp-for="PartnerSelected" asp-items="Model.PartnerItems" style="width:300px;" ></select>
    </div>
    <div>
         <label><b>Сотрудник</b></label><br />
         <select asp-for="ManagerSelected" asp-items="Model.RoleItems" style="width:300px;" ></select>
     </div>
    <div>
        <label><b>Предпочтение</b></label><br />
        <select asp-for="PreferenceSelected" asp-items="Model.PreferenceItems" style="width:300px;" ></select>
    </div>
    <div>
        <br />
        <input type="submit" value="Сохранить" />
        <p>@Model.Message</p>
    </div>
</form>

RazorPagesApp/Pages/PromoCodes/List.cshtml
@page
@model RazorPagesApp.Pages.PromoCodes.ListModel
@{
    ViewData["Title"] = "Список промокодов";
}
<h3>@ViewData["Title"]</h3>

<p><a asp-page="Create">Добавить промокод</a></p>

<table class="table">
    <tr>
        <td><b>Id</b></td>
        <td><b>Код</b></td>
        <td><b>Информация</b></td>
        <td><b>От</b></td>
        <td><b>До</b></td>
        <td><b>Партнер</b></td>
        <td><b>Сотрудник</b></td>
        <td><b>Предпочтение</b></td>
    </tr>
    @foreach (var promoCode in Model.PromoCodeList)
    {
        <tr>
            <td>@promoCode.Id</td>
            <td>@promoCode.Code</td>
            <td>@promoCode.ServiceInfo</td>
            <td>@promoCode.BeginDate.ToString("d")</td>
            <td>@promoCode.EndDate.ToString("d")</td>
            <td>@promoCode.Partner</td>
            <td>@promoCode.PartnerManager</td>
            <td>@promoCode.Preference </td>
            <td>
                <form method="post">
                    <a asp-page="Edit" asp-route-id="@promoCode.Id">Изменить</a>
                    <button type="submit" asp-page-handler="delete" asp-route-id="@promoCode.Id">Удалить</button>
                </form>
            </td>
        </tr>
    }
</table>